---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-dump
  name: kube-dump
  namespace: kube-dump

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-dump
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: kube-dump
    namespace: kube-dump
