---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kube-dump
  name: kube-dump
  namespace: kube-dump
spec:
  serviceAccountName: kube-dump
  containers:
    - name: kube-dump
      image: woozymasta/kube-dump:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 60; done;"]
      volumeMounts:
        - name: data
          mountPath: /data
      resources:
        limits:
          cpu: 500m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 100Mi
  restartPolicy: OnFailure
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: kube-dump
