name: Deploy to manifest to Kubernetes cluster - production

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set up kubectl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} # Use your DigitalOcean API token secret here
            version: 'latest'
  
        - name: Configure kubectl
          run: doctl kubernetes cluster kubeconfig save herams-kubernetes-cluster
  
        - name: Deploy to DigitalOcean Kubernetes
          run: kubectl apply -f kubernetes-manifests/prod/deployment.yaml && kubectl apply -f kubernetes-manifests/prod/ingress.yaml
        
        - name: Validate the application is running
          run: kubectl get all -owide -n portfolio-prod
      
